
import random
import string

def genFiles(names, elements, min_len, max_len):
  """Args:
      names: a list of file names to generate.
      elements: a list of elements appearing in each file,
                the file will be generated by random
      min_len: the minimum length of each file
      max_len: the max length of each file, file length will
               be chosen uniformly from [min_len, max_len]
  """
  for name in names:
    length = random.randint(min_len, max_len)
    f = open(name, 'w')
    for i in range(1, length):
      f.write(random.choice(elements))
    f.close()

def main():
  virus_test_names = ['sample%d.virus' % i for i in range(100)]
  virus_predict_names = ['test%d.virus' % i for i in range(10)]
  virus_names = virus_test_names + virus_predict_names
  virus_elements = string.lowercase[:]

  benigh_test_names = ['sample%d.benigh' % i for i in range(100)]
  benigh_predict_names = ['test%d.benigh' % i for i in range(10)]
  benigh_names = benigh_test_names + benigh_predict_names
  benigh_elements = string.uppercase[:]

  genFiles(virus_names, virus_elements, 100, 1000)
  genFiles(benigh_names, benigh_elements, 100, 1000)




if __name__ == '__main__':
  main()
